ALTER TABLE album
    ADD COLUMN deleted bool NOT NULL DEFAULT FALSE;

ALTER TABLE artist
    ADD COLUMN deleted bool NOT NULL DEFAULT FALSE;

ALTER TABLE genre
    ADD COLUMN deleted bool NOT NULL DEFAULT FALSE;

ALTER TABLE playlist
    ADD COLUMN deleted bool NOT NULL DEFAULT FALSE;

ALTER TABLE track
    ADD COLUMN deleted bool NOT NULL DEFAULT FALSE;