[package]
name = "msgtools"
version = "0.1.0"
authors = ["Marco Rebhan <me@dblsaiko.net>"]
edition = "2021"

[dependencies]
pin-project-lite = "0.2.7"
paste = "1.0.6"
futures = "0.3.17"
thiserror = "1.0.30"